version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8010:8010"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8011:8011"
    volumes:
      - uploads:/app/uploads
    environment:
      - UPLOAD_FOLDER=/app/uploads
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

